### ISSUE TITLE
Change the Address of the application form

### ISSUE THREAD

**Issue by qiyincia** [facetothefate/schoolOffice#1]
麻烦你把我们的入学申请表上的地址改成新地址吧。。谢谢啦
[Application-Form.pdf](https://github.com/facetothefate/schoolOffice/files/562523/Application-Form.pdf)

**Comment by facetothefate** [comment]
好的

Zhifei Fang 方之斐[image: View Zhifei Fang's LinkedIn profile]View Zhifei
Fang's profile http://ca.linkedin.com/in/zhifeifang

http://thefaceteam.org/

2016-10-31 14:16 GMT-04:00 qiyincia notifications@github.com:

**Comment by facetothefate** [comment]
http://www.capital-international.ca/Application-Form.pdf
