### ISSUE TITLE
帮我们把网站上的一句话修改一下吧，谢啦

### ISSUE THREAD

**Issue by qiyincia** [facetothefate/schoolOffice#3]
Come enjoy your study and life here.
We are offering a program of Grade 11-12, which satisfies the Ontario Ministry of Education’s requirements for a Canadian high school diploma. This Program prepares international students for admission to Canadian universities.
这句里面的Grade 11-12改成Grade 10 -12吧。这个比较紧急，麻烦你尽快做吧。谢谢啦！

**Comment by facetothefate** [comment]
已改。
